version: '2'
services:
    ramaadmin-app:
        image: ramaadmin
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ramaadmin-postgresql:5432/ramaadmin
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ramaadmin-postgresql:
        extends:
            file: postgresql.yml
            service: ramaadmin-postgresql
