version: '2'
services:
    ramaadmin-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/ramaadmin/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ramaadmin
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
